#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

setopt GLOB_COMPLETE
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
setopt IGNOREEOF                # so ctrl-d doesn't quit iterm
setopt PUSHD_MINUS
setopt PUSHD_TO_HOME
setopt PUSHD_IGNORE_DUPS
setopt RM_STAR_WAIT

alias 'gs=git status'

alias 'zcp=zmv -C'
alias 'zln=zmv -L'
autoload -U zmv

eval $(thefuck --alias)

export EDITOR='emacs'

LESSPIPE=`which src-hilite-lesspipe.sh`
export LESSOPEN="| ${LESSPIPE} %s"
export LESS=' -R -X -F'

eval "$(direnv hook zsh)"

[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# brew install frum (ruby version manager)
eval "$(frum init)"

# brew install pyenv pipx
# pipx install pipenv
eval "$(pyenv init -)"

# brew install nodenv
eval "$(nodenv init -)"

export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "changyuheng/zsh-interactive-cd"
zplug "clvv/fasd"
zplug "b4b4r07/enhancd"
zplug "Peltoche/lsd"
if ! zplug check --verbose; then
  printf "Install? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi

zplug load

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# heroku autocomplete setup
HEROKU_AC_ZSH_SETUP_PATH=/Users/jay/Library/Caches/heroku/autocomplete/zsh_setup && test -f $HEROKU_AC_ZSH_SETUP_PATH && source $HEROKU_AC_ZSH_SETUP_PATH;

# added by travis gem
[ ! -s /Users/jay/.travis/travis.sh ] || source /Users/jay/.travis/travis.sh

# Created by `pipx` on 2022-01-17 20:49:10
export PATH="$PATH:/Users/jay/.local/bin"

# brew install starship
# this presumably overrides the `Prompt` section of ~/.zpreztorc
eval "$(starship init zsh)"

[ -f "/Users/jay/.ghcup/env" ] && source "/Users/jay/.ghcup/env" # ghcup-env

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
